config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms
  resources :bookings

  root :to => 'bookings#home'
  get 'home' => "bookings#home"

  namespace :api do
    namespace :v1 do
      resources :bookings, only: [:create, :index]
    end
  end

  namespace :api, defaults: {format: 'json'} do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
    end
  end

end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
  <div class="touch-top heading">
      <h3>FOLLOW US</h3>
    </div>
  </div>
  <script type="text/javascript">
                $(document).ready(function() {
                  
                  $().UItoTop({ easingType: 'easeOutQuart' });
                  
                });
              </script>
  <a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
</div>

app/views/shared/_navigation_bar.html.erb
    <div class="header" id="home">
    <div class="container">
      <div class="head">
      <div class="logo">
        <a href="/"><h1 style = "color: white;">HOTEL</h1> </a>
      </div>
      <div class="navigation" id = "navigation_bar">
         <span class="menu"></span> 
          <ul class="navig ">
            <li><a href="/"  class="active hvr-bounce-to-bottom">Home</a></li>
            <li><a href="/rooms" class="hvr-bounce-to-bottom">Rooms</a></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Bookings', bookings_path,class: "hvr-bounce-to-bottom" %></li>
              <li>
                <a class="hvr-bounce-to-bottom" ><%= current_user.email %></a>
              </li>
              <li><%= link_to 'Log out', destroy_user_session_path,class: "hvr-bounce-to-bottom", method: :delete %></li>

              </li>
            <% else %>
               <li><a href="/users/sign_up" class="hvr-bounce-to-bottom"> Sign Up</a></li>
               <li><a href="/users/sign_in" class="hvr-bounce-to-bottom"> Login</a></li>
            <% end %>
          </ul>
      </div>
        <div class="clearfix"></div>
      </div>
      </div>
    </div>  
  <!-- script-for-menu -->
  <!-- script-for-menu -->
    <script>
      $("span.menu").click(function(){
        $(" ul.navig").slideToggle("slow" , function(){
        });
      });
    </script>