config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms
  resources :bookings

  root :to => 'bookings#home'
  get 'home' => "bookings#home"

  namespace :api do
    namespace :v1 do
      resources :bookings, only: [:create, :index]
    end
  end

  namespace :api, defaults: {format: 'json'} do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
    end
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
	enum room_type: ["Deluxe Rooms", "Luxury Rooms", "Luxury suites","Presidential Suites"]
	has_and_belongs_to_many :bookings

  def self.avail_rooms(start_date, last_date, room_type)
  	if Booking.excluded_id(start_date, last_date)
  		self.where("room_type = ? AND id NOT IN (?)", Room.room_types[room_type], Booking.excluded_id(start_date, last_date))
  	else
  		self.where("room_type = ?", Room.room_types[room_type])
  	end
  end

  def room_type_int
    self.class.room_types[self.room_type]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action  :authorize, except: [:index, :show] 
  include ApplicationHelper
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @booking = Booking.new(room_type:@room.room_type)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:price, :rno, :room_type)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :rno %><br>
    <%= f.number_field :rno %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.number_field :room_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_room_0.html.erb
<div class="services-one">
  <div class="flexslider flexslider-padding">
    <ul class="slides">
      <li>
        <%= link_to image_tag("room_0", class: "img-responsive",height: 300, width: 450), new_booking_path(room_type:0)%>
      </li>
      <li>
        <%= link_to image_tag("room_0_1", class: "img-responsive",height: 300, width: 450), new_booking_path(room_type:0)%> 
      </li>
      <li>
        <%= link_to image_tag("room_0_2", class: "img-responsive",height: 300, width: 450), new_booking_path(room_type:0)%>
      </li>
    </ul>
    <div class="clearfix"></div>
  </div>

  <h4>Deluxe Rooms - Queen Size Bed</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li><a href="#">Queen Size Bed</a></li>
    <li><a href="#">Beautifu Views</a></li>
  </ul>
</div>

app/views/rooms/_room_1.html.erb
<div class="services-one">
  <section class="slider">
    <div class="flexslider flexslider-padding">
      <ul class="slides">
        <li>
          <%= link_to image_tag("room_1", class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:1)%>
        </li>
        <li>
          <%= link_to image_tag("room_1_1", class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:1)%>
        </li>
        <li>
          <%= link_to image_tag("room_1_2", class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:1)%>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
  </section>
  <h4>Luxury Rooms - Queen Size Bed and Pool Facing</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li><a href="#">Queen Size Bed</a></li>
    <li><a href="#">Swimming Pool</a></li>
  </ul>
</div>

app/views/rooms/_room_2.html.erb
<div class="services-one">
  <div class="flexslider flexslider-padding">
    <ul class="slides">
      <li>
        <%= link_to image_tag("room_2",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:2)%>
      </li>
      <li>
        <%= link_to image_tag("room_2_1",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:2)%>
      </li>
      <li>
        <%= link_to image_tag("room_2_2",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:2)%>
      </li>
    </ul>
    <div class="clearfix"></div>
  </div>
  <h4>Luxury Suites - King Size Bed and Pool Facing</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li><a href="#">King Size Bed</a></li>
    <li><a href="#">Swimming Pool</a></li>
  </ul>
</div>

app/views/rooms/_room_3.html.erb
<div class="services-one">
  <section class="slider">
    <div class="flexslider flexslider-padding">
      <ul class="slides">
        <li>
          <%= link_to image_tag("room_3",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:3)%>
        </li>
        <li>
          <%= link_to image_tag("room_3_1",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:3)%>
        </li>
        <li>
          <%= link_to image_tag("room_3_2",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:3)%>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
  </section>
  <h4>Presidential Suites - King Size Bed, Pool Facing with a Gym</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li><a href="#">King Size Bed</a></li>
    <li><a href="#">Swimming Pool</a></li>
  </ul>
  <div class="clearfix"></div>        
</div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
  <div class="services">
    <div class="container">
      <div class="services-top heading">
        <h3>Room categories</h3>
      </div>
      <div class="services-bottom">
        <div class="col-md-6 services-left">
          <%= render "room_0" %>
          <%= render "room_1" %>
        </div>
        <div class="col-md-6 services-right">
          <%= render "room_2" %>
          <%= render "room_3" %>
        </div>
      </div>
    </div>
  </div>
  <!--end-services-->
  <!--start-special-->
  <div class="special">
    <div class="container">
      <div class="special-main">
        <div class="col-md-6 special-left heading">
          <h3>SPECIAL PROPOSITION</h3>
        </div>
        <div class="col-md-6 special-left">
              <p>Appealing to leisure and business travelers who want to experience their destination cities like real locals, Airbnb offers a way to stay in unconventional lodging (often for less than their big brand hotel counterparts).
               However, Airbnb’s value proposition is not economy accommodations. The benefit of using Airbnb is discovering the full richness of travel by being submerged in the local culture and new settings.</p>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<div class="services">
  <div class="container">
		<div class="col-md-6 services-left">
			<%= render "room_#{@room.room_type_int}"%>
		</div>
		<div class="col-md-6 services-right" style = "background-color: #ADD8E6;">
			<%= render "bookings/form"%>
		</div>
	</div>
</div>